### ISSUE TITLE
Time series data

### ISSUE THREAD

**Issue by Sushmitha46** [STREAmS-CFD/STREAmS-2#1]
Hello,
I am trying to do low frequency unsteadiness study for sbli case and I wanted to know how to obtain time series data.
Is it possible for us to change few parameters in input.dat and get time-series data or should we ourselves make changes in code to get that data?
(I need data for every iteration with elapsed time and properties)

Thank You

**Comment by JihoonKimKorea** [comment]
Hi! 
Did you solve this problem? I also need time series data.
