### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by OYYO1999** [STREAmS-CFD/STREAmS-2#10]
Hi, I followed the same steps as given in the user guide to compile the code but got this error.

![issue1](https://github.com/user-attachments/assets/5f1e11ad-a4ac-4b7c-b056-a48b84ff82f5)

please give my some tips.

**Comment by francescosalvadore** [comment]
Hi, which compiler/version are you using? What does makefile.inc contain?

**Comment by OYYO1999** [comment]
ohh, thanks for your answer!
I am using gfortran and g++ in Ubuntu2206, as follow:
![g++](https://github.com/user-attachments/assets/cb2d2ce8-67ef-4903-8e98-965997ff9810)
![gfortran](https://github.com/user-attachments/assets/660865fd-1407-4e46-9b3d-fd7cbc0edcb4)
The file makefile.inc in ./STREAmS-2/code/.
![code_make](https://github.com/user-attachments/assets/8d332d78-37ea-4107-a364-acf893ec93c9)

**Comment by OYYO1999** [comment]
The makefile.inc include as follow:
![makefile inc](https://github.com/user-attachments/assets/343ec44a-14a8-4b22-be66-0ebbb8da39d6)

**Comment by francescosalvadore** [comment]
gfortran 4.7.4 is too old probably. try to update/reinstall it. g++ 11 is ok.

**Comment by OYYO1999** [comment]
thanks, I have compiled！
But i want ask some questions, as follow:
1. If I want to add some roughness to the channel surface, how do I manipulate my mesh?
2. How to add some source terms to the equation?

**Comment by francescosalvadore** [comment]
To simulate roughness you probably need major development (e.g., immersed boundary).

A simple forcing can be added as a new procedure to be called from rk_sync/rk_async.

**Comment by OYYO1999** [comment]
This is a shame, you will update the code further so that it can simulate roughness surfaces.
OK, thanks for your answer,

**Comment by davidem88** [comment]
At the moment, we are not planning to add roughness in the public repository.
For modeled roughness you can look at this thesis https://repository.tudelft.nl/record/uuid:659437ca-4dcf-47ea-beb3-4e3557d9e9bc, where modeled roughness was implemented in streams.

The method used was the one proposed by Busse&Sandham https://doi.org/10.1017/jfm.2012.408

**Comment by OYYO1999** [comment]
oh! thanks for your answer and referenece!
