### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by CFDER-HF** [STREAmS-CFD/STREAmS-2#11]
Hi,
I'm follwing the user guide for compliling but encountered some fatal errors:

root@node2:/home/soft/STREAmS-2/code# make -j32
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/cfgio/string_conv_mod.F90 -o build/third-party/cfgio/string_conv_mod.o -module build/mods
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/cfgio/cfgio_mod.F90 -o build/third-party/cfgio/cfgio_mod.o -module build/mods
gcc -O2 /home/soft/openmpi-5.0.5/include -c third-party/crandom/crandom.c -o build/third-party/crandom/crandom.o
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/crandom/crandom_f.F90 -o build/third-party/crandom/crandom_f.o -module build/mods
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/cpumem/getmeminterface.F90 -o build/third-party/cpumem/getmeminterface.o -module build/mods
gcc -O2 /home/soft/openmpi-5.0.5/include -c third-party/cpumem/getmemory.c -o build/third-party/cpumem/getmemory.o
g++ -std=c++17 -frounding-math -O2 /home/soft/openmpi-5.0.5/include -c third-party/cgal/cgal_c_wrappers_dummy.cpp -o build/third-party/cgal/cgal_c_wrappers_dummy.o
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/cgal/cgal_f90_wrappers.F90 -o build/third-party/cgal/cgal_f90_wrappers.o -module build/mods
g++ -std=c++17 -frounding-math -O2 /home/soft/openmpi-5.0.5/include -c third-party/catalyst/catalyst_adaptor_c_dummy.cxx -o build/third-party/catalyst/catalyst_adaptor_c_dummy.o
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/catalyst/catalyst_adaptor_dummy.F90 -o build/third-party/catalyst/catalyst_adaptor_dummy.o -module build/mods
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c third-party/catalyst2/catalyst2_dummy.F90 -o build/third-party/catalyst2/catalyst2_dummy.o -module build/mods
mpif90  /home/soft/openmpi-5.0.5/include -O3 -cuda -gpu=sm_70 -c src/parameters.F90 -o build/src/parameters.o -module build/mods
make: *** No rule to make target 'build/mods/streams_parameters.mod', needed by 'build/src/grid.o'.  Stop.
make: *** Waiting for unfinished jobs....
gcc: warning: /home/soft/openmpi-5.0.5/include: linker input file unused because linking not done
gcc: warning: /home/soft/openmpi-5.0.5/include: linker input file unused because linking not done
g++: warning: /home/soft/openmpi-5.0.5/include: linker input file unused because linking not done
g++: warning: /home/soft/openmpi-5.0.5/include: linker input file unused because linking not done
third-party/cfgio/string_conv_mod.F90:
third-party/cfgio/cfgio_mod.F90:
NVFORTRAN-F-0004-Unable to open MODULE file string_conv_mod.mod (third-party/cfgio/cfgio_mod.F90: 6)
NVFORTRAN/x86-64 Linux 24.5-1: compilation aborted
make: *** [Makefile:199: build/third-party/cfgio/cfgio_mod.o] Error 2
third-party/crandom/crandom_f.F90:
third-party/cfgio/string_conv_mod.F90:
third-party/cpumem/getmeminterface.F90:
third-party/catalyst/catalyst_adaptor_dummy.F90:
third-party/cgal/cgal_f90_wrappers.F90:
third-party/catalyst2/catalyst2_dummy.F90:

My system is ubuntu 20.04 and the GPU is V100. I'm using gcc 9.3.0, cuda-12.4 and my configuration file is
#----------------------------------------------------------------------
EQUATION = "singleideal"
BACKEND  = "gpu=sm_70"
COMPILE  = "nv-cuda"
MODE     = "opt"
PREC     = "double"
CUDA_VER = 12.4
MPI_CMD  =

Looking forward to your kindly help!

**Comment by francescosalvadore** [comment]
Try to recompile without -j32

**Comment by CFDER-HF** [comment]
It works. Thanks a lot!

**Comment by CFDER-HF** [comment]
Hi, I tried to run the supersonic channel flow case. The progress.out looks well as expected. However, the values in POSTPRO files are all Nan. How could I deal with it? 
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/65453eb8-5242-45bd-b42f-d3c30aaa2bcd">

**Comment by davidem88** [comment]
Did you pull the most recent version of the code and postprocessing?

**Comment by CFDER-HF** [comment]
Yes I did.

**Comment by CFDER-HF** [comment]
These are all the ouput files generated and the way I run POSTPRO
<img width="609" alt="image" src="https://github.com/user-attachments/assets/562f847a-f8b6-4c70-a897-0949ca0949bf">

**Comment by davidem88** [comment]
Can you attach your input file, singleideal.ini?

**Comment by CFDER-HF** [comment]
Certainly!

; Input file for: STREAmS 2.0
; This file provides typical parameters for the simulation of a supersonic turbulent channel.
; Parameters are selected only for demonstration purposes, not for a production run. 

[grid]
domain_size_x =  6      ; domain size in x direction
domain_size_y =  2.     ; domain size in y direction
domain_size_z =  3.     ; domain size in z direction
nxmax         = 512     ; total number of grid nodes in x direction (must be multiple of x_split)
nymax         = 300     ; total number of grid nodes in y direction
nzmax         = 384     ; total number of grid nodes in z direction (must be multiple of z_split)
ng            = 3       ; total number of ghost nodes
metrics_order = 6       ; order of accuracy for metrics computation
grid_type     = 3       ; mesh type: 1=> FROMFILE, 2=> UNI, 3=> CHA, 4=> BL
dyptarget     = .8      ; wall-normal spacing at the wall in wall-units (active for grid_type = 3,4)
jbgrid        = 32      ; used for piros type grid (must be > 0, suggested values 16,32,64)
nywr          = 140     ; nodes in "well-resolved region (piros)" for BL (baseline choice ny = nint(4./3/(1.25*0.8)*(ret*lywr)**0.75)
lywr          =  2.     ; size of "well-resolved region (piros)" for BL
ysmoosteps    = 50      ; number of steps for smoothing grid in y direction (suggested value for BL 10, for CHA 100)

[bc]                    ; flags for boundary conditions
xmin = 0                ; 0  ==> periodic bc
xmax = 0                ; 1  ==> freestream
ymin = 6                ; 2,4  ==> supersonic and subsonic (pressure imposed) extrapolation (zero-order)
ymax = 6                ; 5  ==> symmetry (inviscid adiabatic wall)
zmin = 0                ; 6  ==> viscous wall (staggered for channel case)
zmax = 0                ; 7  ==> oblique shock 
xmin_nr = 0             ; 9,10 ==> laminar or turbulent (recycling-rescaling) turbulent inflow
xmax_nr = 0             ; flags for non-reflecting treatment
ymin_nr = 0             ; 0 ==> nothing
ymax_nr = 0             ; 1 ==> pure non-reflecting
zmin_nr = 0             ; 2 ==> relax (Pirozzoli and Colonius JCP 2013)
zmax_nr = 0             ; 6 ==> reflective wall
x_recyc = 40.           ; recycling location
correct_bound_ord = 1   ; apply correction to reduce order at boundaries (>0 to activate)

[mpi]                   ; MPI split
x_split =  2            ; MPI partitions in x direction
y_split =  1            ; MPI partitions in y direction (should be 1)
z_split =  2            ; MPI partitions in z direction

[controls]
restart_type = 0         ; 0 => new run from scratch, 1=> continue previous run, 2=> continue previous run and statistics
cfl = 0.75               ; >0 CFL, <0 time step of the simulation
iter_dt_recompute = 1    ; frequency for re-computation of time step
num_iter =   100          ; number of RK steps

[numerics]
ep_order   = 6           ; order of accuracy for the discretization of convective terms (central scheme energy and entropy preserving, KEEP)
nkeep      = 0           ; < 0 KEP scheme, >=0 KEEP(n) scheme
visc_order = 2           ; order of accuracy for the discretization of viscous terms
conservative_viscous = 1 ; flag to activate computation of viscous terms in conservative form
weno_scheme = 3          ; Weno parameter (order of accuracy = 2*weno_scheme-1)
weno_version = 1         ; Weno version (0 -> Jian and Shu, 1 -> WenoZ)
sensor_threshold = .4    ; threshold value for shock sensor
rk_type   = 1            ; RK type: 1 => WRAY RK
rand_type = 2            ; <0 random not reproducible, =>0 random reproducible
mode_async = 0           : 0 -> synchrouns communication pattern, 1 -> async

[flow]
flow_init     = 0        ; -1 => windtunnel, 0 => CHA, 1 => BL, SBLI, 2 => TGV
Mach          = 2.       ; Mach number (freestream for WT, BL and SBLI, bulk for CHA based on Tbulk if theta_wall>=-1., on Twall otherwise)
Reynolds      = 490.     ; Reynolds number (friction)
theta_wall    = .35      ; wall temperature condition (Tw-Tinf)/(Tr-Tinf) for BL and SBLI, (Tw-Tb)/(Tr-Tb) for CHA (if < -1. Tbulk free to evolve)
xshock_imp    = 80.      ; oblique shock impingment location
shock_angle   = 34.1     ; oblique shock angle
T_ref         = 220.     ; reference dimensional temperature

[fluid]
gam        = 1.4         ; specific heat ratio (for calorically-perfect gases)
Prandtl    = 0.72        ; Prandtl number
visc_model = 2           ; viscosity temperature relation: 0 => inviscid, 1=> power law, 2=> Sutherland law
vt_exp     = 0.76        ; exponent for power law
s_suth     = 110.4       ; Sutherland constant (dimensional)
calorically_perfect = 1  ; 1=>constant cp, 0=> variable cp via cp_coeff
indx_cp_l   = -2         ; exponent low limit of cp polynomial
indx_cp_r   = 4          ;  exponent high limit of cp polynomial
cp_coeff   = 1.009950160D+04, -1.968275610D+02, 5.009155110D+00, -5.761013730D-03, 1.066859930D-05, -7.940297970D-09, 2.185231910D-12 ; coefficients for cp(T) polynomial

[output]
print_control = 1     ; frequency for printing output file progress.out
dtsave_restart = 50.  ; frequency for saving restart files (rst.bin and finaltime.dat)
dtsave  = 10.         ; frequency for saving plot3d and vtk files
dtstat  = 10.         ; frequency for computing statistics (2D and 3D)
dtslice = 50.         ; frequency for writing slices
enable_stat_3d = 1    ; enable computation of 3D statistics
enable_plot3d = 1     ; enable writing of plot3d files (1 => yes)
enable_vtk = 1        ; enable writing of vtr files (1 => yes)
igslice = 0           ; list of (global) indices for yz-slices
jgslice = 0           ; list of (global) indices for xz-slices
kgslice = 1           ; list of (global) indices for xy-slices
debug_memory = 0      ; check memory for CPU and GPU (0 => no, 1 => yes)

**Comment by davidem88** [comment]
This is just because you haven't run for long enough to collect statistics. Reduce the interval at which statistics are collected (e.g. dtstat=0.1) and run for longer (e.g. 1000 steps).
