### ISSUE TITLE
GPU version calculation error

### ISSUE THREAD

**Issue by JihoonKimKorea** [STREAmS-CFD/STREAmS-2#12]
Hi, I'm trying to compile gpu version but have some issues.

Initialization went well, but the calculation was something strange.

I've attached solving progress here.

 Random numbers reproducible
 Geometric progression factor rgp =    1.003243988161555     
 Gamma:     1.400000000000000     
 Input friction Reynolds number:     600.0000000000000     
 Reynolds based on free-stream properties:     40611.26805469919     
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  0  528771125248  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  1  528540430336  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  4  528370229248  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  3  528337199104  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  2  528275783680  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  5  528275783680  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  8  528275783680  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  11  528275783680  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  6  528263397376  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  10  528213852160  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  7  528180822016  540623142912
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  9  528180822016  540623142912
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  5  527000543232  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  5  22023307264  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  6  527000543232  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  6  22023307264  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  10  526805057536  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  10  21488533504  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  7  526796800000  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  7  21488533504  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  0  526780284928  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  0  21350121472  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  11  526745219072  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  11  21205417984  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  1  526739628032  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  1  21067005952  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  4  526716977152  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  4  20653867008  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  3  526716977152  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  3  20651769856  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  9  526716260352  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  9  20651769856  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  8  526642544640  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  8  20511260672  25407520768
CPU rank,mems:   --initialize-start--  kucfd-System-Product-Name  2  526367006720  540623142912
gpu rank,mems:   --initialize-start--  kucfd-System-Product-Name  2  20372848640  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  5  525697945600  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  5  20372848640  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  6  525697945600  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  6  19900989440  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  0  525689458688  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  0  19429130240  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  1  525689458688  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  1  18957271040  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  7  525697716224  540623142912
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  3  525697716224  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  3  18307153920  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  10  525697716224  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  10  18485411840  25407520768
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  7  18307153920  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  8  525697257472  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  8  17069834240  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  11  525697257472  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  11  16597975040  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  4  525697257472  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  4  16126115840  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  9  525697257472  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  9  15947857920  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  5  525697257472  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  5  15255797760  25407520768
--------------------------------------------------------------------------
The call to cuMemHostRegister(0x77e643e00008, 134217728, 0) failed.
  Host:  kucfd-System-Product-Name
  cuMemHostRegister return value:  1
  Registration cache:  smcuda
--------------------------------------------------------------------------
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  6  525696528384  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  6  15182397440  25407520768
CPU rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  2  525696528384  540623142912
gpu rank,mems:   --initialize-first-gpu-usage--  kucfd-System-Product-Name  2  15182397440  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  0  525696528384  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  0  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  1  525696528384  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  1  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  3  525696528384  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  3  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  10  525696528384  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  10  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  8  525696012288  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  8  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  7  525691895808  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  7  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  2  525691895808  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  2  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  11  525690892288  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  11  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  4  525690892288  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  4  14710538240  25407520768
CPU rank,mems:   initialize-completed  kucfd-System-Product-Name  9  525690892288  540623142912
gpu rank,mems:   initialize-completed  kucfd-System-Product-Name  9  14710538240  25407520768
 Storing VTK sol            0 at time    0.000000000000000     
 dt =   8.2290803432359520E-004
 dt*u0/l0 =   2.1907753133454297E-003
 random numbers reproducible
 time_from_last_stat=   8.2290803432359520E-004
 itav =            0
[kucfd-System-Product-Name:15265] 11 more processes have sent help message help-mpi-common-cuda.txt / cuMemHostRegister during init failed
[kucfd-System-Product-Name:15265] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
 time_from_last_slice=   8.2290803432359520E-004
 time_from_last_probe=   8.2290803432359520E-004
         1    8.2290803432E-04    8.2290803432E-04                 NaN    1.7976931349+308   -1.0000000000E+02    1.7976931349+308   -1.0000000000E+02    1.7976931349+308   -1.0000000000E+02
 time_from_last_write=                       Inf
 istore =            1
 Storing VTK sol            1 at time   8.2290803432359520E-004
 time_from_last_stat=                       Inf
 itav =            1
 time_from_last_slice=                       Inf
 time_from_last_probe=                       Inf
 time_from_last_rst=                       Inf
 Writing rst.bin
         2                 Inf                 Inf                 NaN    1.7976931349+308   -1.0000000000E+02    1.7976931349+308   -1.0000000000E+02    1.7976931349+308   -1.0000000000E+02
 time_from_last_write=                       Inf
 istore =            2
 Storing VTK sol            2 at time                       Inf
 time_from_last_stat=                       Inf
 itav =            2
 time_from_last_slice=                       Inf
 time_from_last_probe=                       Inf
 time_from_last_rst=                       Inf
 Writing rst.bin

Furthermore, when I tried running with probe_list.dat, the calculation didn't start because of MPI issue in my opinion.

 Random numbers reproducible
 Geometric progression factor rgp =    1.003243988161555     
 Gamma:     1.400000000000000     
 Input friction Reynolds number:     600.0000000000000     
 Reynolds based on free-stream properties:     40611.26805469919     
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
FIO-F-217/list-directed read/unit=18/attempt to read past end of file.
 File name = 'probe_list.dat',    formatted, sequential access   record = 15
 In source file src/singleideal/singleideal.F90, at line number 628
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[16837,1],0]
  Exit code:    127

**Comment by davidem88** [comment]
Can you specify what makefile.inc you're using and what hardware? In addition, can you add your input file (singleideal.ini) and probe_list.dat file?

**Comment by JihoonKimKorea** [comment]
Thanks for reply on this issue.
The operating system I'm using is Ubuntu 22.04.

I've attached screenshots for the makefile.inc, input file, and probe_list.dat file.

Also, I've attached information of GPU.

![image](https://github.com/user-attachments/assets/b1978c49-f0d0-43cd-8235-6d418bfc86a0)

![image](https://github.com/user-attachments/assets/9e163106-9cf2-40b3-904b-e086d5399efd)
![image](https://github.com/user-attachments/assets/70f9fae0-a7a4-40a1-86e7-8ff07e1c01dd)

![image](https://github.com/user-attachments/assets/42c9428d-7034-44bc-9869-7070f6ae791a)

![image](https://github.com/user-attachments/assets/cf58ac5a-3465-490f-9571-e701731d8316)

**Comment by davidem88** [comment]
Regarding the probe_list.dat, there's a syntax error. For each probe you need 4 numbers per row. The first is the probe id, then the three spatial coordinates (see singleideal.F90, line 623).
For the other issues, please attach the actual files, not just screenshots.

**Comment by JihoonKimKorea** [comment]
Thanks for letting me know the location of the code about probe.

I figured out that some remaining files in working directory caused the calculation issues.

The calculation works, but it seems that the gpu doesn't work when calculation starts.

I've attached singleideal.ini and makefile.inc files.

[files.zip](https://github.com/user-attachments/files/18058233/files.zip)

And I got this kind of error at this moment.

 Random numbers reproducible
 Geometric progression factor rgp =    1.032724826679856     
 Gamma:     1.400000000000000     
 Input friction Reynolds number:     600.0000000000000     
 Reynolds based on free-stream properties:     40611.26805469919     
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  1  530484232192  540624625664
 Recycling station exactly at =     20.00000000000000     
 Recycling beta factor =     1.030061873244340     
 Pirozzoli-Ceci beta factor =     1.030381857965625     
 Urbin-Knight beta factor =     1.095587981098094     
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  6  530475974656  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  10  530475974656  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  2  530475974656  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  0  530451202048  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  3  530442944512  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  4  530442944512  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  5  530442944512  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  11  530426429440  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  8  530426429440  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  7  530401656832  540624625664
CPU rank,mems:   --base-initialization--  kucfd-System-Product-Name  9  530393399296  540624625664
--------------------------------------------------------------------------
**The call to cuMemHostRegister(0x7e175fe00008, 134217728, 0) failed.
  Host:  kucfd-System-Product-Name
  cuMemHostRegister return value:  1
  Registration cache:  smcuda**
--------------------------------------------------------------------------
 Storing VTK sol            0 at time    0.000000000000000     
[kucfd-System-Product-Name:04075] 11 more processes have sent help message help-mpi-common-cuda.txt / cuMemHostRegister during init failed
[kucfd-System-Product-Name:04075] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
 dt =   7.0709236971418731E-004
 dt*u0/l0 =   1.8824466929625461E-003
 random numbers reproducible
 time_from_last_stat=   7.0709236971418731E-004
 itav =            0
 time_from_last_slice=   7.0709236971418731E-004
 time_from_last_probe=   7.0709236971418731E-004
         1    7.0709236971E-04    7.0709236971E-04    2.6556172226E-01    5.1666230792E-01    1.0029840023E+00    9.9878623649E-01    1.9106522318E+00    9.8127756887E-01    1.0182627710E+00
 time_from_last_stat=   7.0832668822658998E-004
 itav =            1
 time_from_last_slice=   7.0832668822658998E-004
 time_from_last_probe=   7.0832668822658998E-004
         2    7.0832668823E-04    1.4154190579E-03    2.6294226349E-01    5.1132485178E-01    1.0063527119E+00    9.9730059910E-01    1.9142561093E+00    9.6805443795E-01    1.0333067391E+00
 time_from_last_stat=   7.1111312373945443E-004
 itav =            2
 time_from_last_slice=   7.1111312373945443E-004
 time_from_last_probe=   7.1111312373945443E-004
         3    7.1111312374E-04    2.1265321817E-03    2.6236536023E-01    5.0979020861E-01    1.0102189731E+00    9.9556705772E-01    1.9159970703E+00    9.5230760111E-01    1.0481201457E+00
 time_from_last_stat=   7.0828902952907002E-004
 itav =            3
 time_from_last_slice=   7.0828902952907002E-004
 time_from_last_probe=   7.0828902952907002E-004
         4    7.0828902953E-04    2.8348212112E-03    2.6340559575E-01    5.1088826967E-01    1.0135737431E+00    9.9361153629E-01    1.9160512912E+00    9.3921598076E-01    1.0588357892E+00
 time_from_last_stat=   7.0738479500045807E-004
 itav =            4
 time_from_last_slice=   7.0738479500045807E-004
 time_from_last_probe=   7.0738479500045807E-004
         5    7.0738479500E-04    3.5422060062E-03    2.6576059944E-01    5.0977709931E-01    1.0172085958E+00    9.9169858561E-01    1.9166113951E+00    9.2861246764E-01    1.0690580013E+00

**Comment by davidem88** [comment]
Anyway, the simulation is running, so you're using the 12 GPUs. I think you can ignore those messages. 
I see that you're storing slices and collecting statistics every time step. That will slow down your computation and it is probably not needed to save this often.

**Comment by JihoonKimKorea** [comment]
I can use 3 GPUs, so I need to change mpi splits into 3.

Yes you're right, I'm able to reduce the period of collecting data. Thank you so much Prof. Modesti.

I will open new issues when I have questions or problems.

**Comment by JihoonKimKorea** [comment]
Yes, I recognize it! Thanks for your comments.
