### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by barbariansubhkaran** [STREAmS-CFD/STREAmS-2#8]
Hello sir, I followed the same steps as given in the user guide to compile the code but got this error. Please help me.  

Fatal Error: Cannot open module file 'build/mods/string_conv_mod.mod0' for writing at (1): No such file or directory
compilation terminated.
make: *** [Makefile:199: build/third-party/cfgio/string_conv_mod.o] Error 1

**Comment by davidem88** [comment]
What compiler and what makefile.inc are you using?
