### ISSUE TITLE
T_bulk level in compressible  supersonic channel flow

### ISSUE THREAD

**Issue by HaoqiFei1** [STREAmS-CFD/STREAmS-2#9]
I conducted a simulation of compressible channel flow at Re_tau=500 and Ma=1.5. The velocity profile and Reynolds stress are agree well with the results of available literature. But the T_bulk profile is significantly higher than the results of equivalent settings in the literature. The simulation has run a long time but we don't see any trend of T_bulk decreasing.  Did we make a mistake in .ini file？ 
[singleideal_ini.txt](https://github.com/STREAmS-CFD/STREAmS-2/files/15495968/singleideal_ini.txt)

**Comment by davidem88** [comment]
Dear HaoqiFei1,

I see you set visc_order = 3. This is incorrect. Viscous terms are always discretized with a central scheme. If conservative_viscous = 1, then visc_order = 2. If conservative_viscous = 0 then visc_order can be set to 2,4 or 6.

I also see that you're using sensor_threshold = 0.05. For a plane channel flow at M=1.5 you don't need to use WENO, therefore, you can set sensor_threshold>1. The simulation will be substantially faster.

**Comment by HaoqiFei1** [comment]
Dear davidem88，

Thank you for your guidence. I'm new to the STREAmS-2, so I just did that by modifying the example you provided. A lot of the parameters stayed the same.

You guys did a great job, but I hope you can improve the mistakes in providing examples to avoid being misunderstood.

Haoqi Fei
Shanghai Jiao Tong University
No.800, Dongchuan Road, Minhang District, Shanghai, China
***@***.***

----- 原始邮件 -----
发件人: "davidem88" ***@***.***>
收件人: "STREAmS-CFD/STREAmS-2" ***@***.***>
抄送: "HaoqiFei1" ***@***.***>, "Author" ***@***.***>
发送时间: 星期三, 2024年 10 月 23日 下午 8:52:36
主题: Re: [STREAmS-CFD/STREAmS-2] T_bulk level in compressible  supersonic channel flow (Issue #9)

Dear HaoqiFei1,

I see you set visc_order = 3. This is incorrect. Viscous terms are always discretized with a central scheme. If conservative_viscous = 1, then visc_order = 2. If conservative_viscous = 0 then visc_order can be set to 2,4 or 6.

I also see that you're using sensor_threshold = 0.05. For a plane channel flow at M=1.5 you don't need to use WENO, therefore, you can set sensor_threshold>1. The simulation will be substantially faster.

**Comment by davidem88** [comment]
Thank you. Another possible problem I noticed is nymax is slightly too coarse. We use the grid stretching described in this paper https://doi.org/10.1016/j.jcp.2021.110408 The total number of points in the wall normal direction can be estimated using equation (8) (also table 2), which results in about nymax=280 points for a plane channel flow.

Also, pull the most recent version of the solver as there have been some corrections/updates.
